[theme]
base = "light"
primaryColor = "#24557A"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#17212B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
